[package]
name = "galahad-actix"
version = "0.1.0"
edition = "2021"
description = "Actix integration for Galahad"
license = "MIT"

[lib]
path = "src/lib.rs"

[features]
default = []
openapi = ["dep:utoipa"]

[dependencies]
actix-web = "4"
galahad-core = { path = "../galahad-core" }
serde = { version = "1", features = ["derive"] }
utoipa = { version = "5", optional = true }
